-- Import clienti da Fresha
-- Generato: 2026-01-02 14:48:15
-- Business ID: 1

DELETE FROM clients WHERE business_id = 1;

INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Pina', 'Lesina', NULL, '+393475202281', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Vincenza', 'Paglia', NULL, '+39069375319', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Simone', 'Antonelli', 'antonelli042@gmail.com', '443318806451', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Alessandra', 'Razzi', NULL, '+393391631353', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Roberta', 'Sette', 'roberta.registrazioni@gmail.com', '+393470957826', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Sara', 'Melaranci', 'sara.melaranci@hotmail.it', '+393339787506', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Paola', 'Trombetta', NULL, '+393495922637', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Simona', 'Savini', 'simonasavi@yahoo.it', '+393358086891', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Alessandro', 'Capelli', NULL, '+393332711180', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Colomba', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Renzo', 'Palazzine', NULL, '+393801953827', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Pomponi', 'Maria', NULL, '+393896479778', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Daniela', 'Laucella', 'daniela.laucella@gmail.com', '+393333969635', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Agnese', 'Kilar', 'agnesekilar75@gmail.com', '+393505171464', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Alessandro', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Pietro', 'Iptv', NULL, '+393496786762', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Mario', 'Vicente', NULL, '+393279277278', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Olga', 'Facchin', NULL, '+393475899994', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Gabriella', 'Fabiani', NULL, '+393474658050', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Filomena', 'Roccasecca', 'filomenaroccasecca9@gmail.com', '+393487627374', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Punam', 'Zevini', NULL, '+393491784877', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Massimo', 'Giordano', NULL, '+393333674220', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Cinzia', 'Carliseppe', NULL, '+393409675288', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Mirko', 'Gentili', NULL, '+393470540202', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Francesco', 'Tudini', NULL, '+393202661813', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Luciano', 'Greco', 'herosjeans@alice.it', '+393252135460', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Julie Anne', 'Lawlor Holmes', 'juleslholmes@gmail.com', '353868105588', 'Donna', '1971-03-23', NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Valentina', 'Fuselli', 'fuselli92@gmail.com', '+393498276465', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Gianmarco', 'Furzi', NULL, '+393201636430', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Samuele', 'Amici', 'samueleamici57@gmail.com', '+393425599462', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Mauro', 'Venditti', NULL, '+393426619770', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Marco', 'Vigile', NULL, '+393286667962', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Antonella', 'Gianfagna', NULL, '+393937196637', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Miriana', 'Sociale', NULL, '+393497899598', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Elisabetta', 'Di pietro', NULL, '+393471935909', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Valeria', 'Simonetti', NULL, '+393472581688', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Corrado', NULL, NULL, '+393406363892', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Laura', 'Grassi', NULL, '+393314704818', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Maria Elisa', 'Cardelli', NULL, '+393389951792', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Eliana', 'Giangreco', NULL, '+393494456867', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Simone', 'Manuel', NULL, '+393896469881', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Maria', 'Gozzi', NULL, '+393403891038', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Luisa', 'Mariani', NULL, '+393403872021', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Francesca', 'Brozzi', NULL, '+393477743616', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Flavio', 'Ciccarelli', 'flaviocicc@icloud.com', '+393492548041', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Alvisia', 'Ciampanella', NULL, '+393400859109', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Ivana', 'Servadio', NULL, '+393470371505', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Denise', 'Galli', NULL, '+393475772408', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Fabiana', NULL, NULL, '+393497894595', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Antonella', 'D alessio', NULL, '+393339786307', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Nicola', 'Pinto', NULL, '+393407864635', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Margot', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Teresa', 'Romani', NULL, '+393494572912', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Lucia', 'Innocenzi', NULL, '+393408944161', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Pina', 'Golia', NULL, '+39069376059', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Alberto', 'Frezza', NULL, '+393313357256', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Raffaella', 'D alessio', NULL, '+393473349419', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Marisa', 'Alunni', NULL, NULL, NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Susy', 'Izzo', NULL, '+393476319985', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Annalisa', 'De carolis', NULL, '+393492568566', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Autino', 'Rosa', NULL, '+39069375964', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Marta', 'Trombetta', 'marta.trombetta89@gmail.com', '+393290173730', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Dario', 'Trombetti', NULL, '+393701571198', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'John', 'Mazzarella', NULL, '+393403975229', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Federica', 'Izzo', 'federica.izzo87@gmail.com', '+393494332922', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Diego', 'Passamonti', NULL, '+393459776974', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Giulia', 'Lucia', NULL, '+393479700763', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Lorenzo', 'Taddeo', NULL, '+393348082359', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Olympia', 'Frezza', NULL, '+393888104138', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Carmela', 'Bernardi', NULL, '+393288624159', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Assunta', 'Izzo', 'susyizzo82@gmail.com', '+393475729521', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Luigia', 'Tamburro', NULL, '+393481687644', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Tina', 'Adiutori', NULL, '+393473443048', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Marina', 'Fiandra', NULL, '+393482366402', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Monica', 'Santucci', NULL, '+393383156102', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Erika', 'Falco', NULL, '+393402555703', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Jacopo', 'Cofini', 'gmmydhf7q9@privaterelay.appleid.com', '+393281529542', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Alessio', 'Amici', NULL, '+393758506079', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Alessandra', 'Calvitti', NULL, '+393343427051', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Paola', 'Papotti', NULL, '+393469611932', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Giorgia', 'Rossi', NULL, '+393470737949', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Andrea', 'Garofalo', 'garand73@gmail.com', '+393476692836', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Elena', 'Colafigli', 'ecolafigli@alice.it', '+393280420784', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Enrico', 'Marsiniano', NULL, '+393341065906', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Marco', 'Pizza re', NULL, '+393801738922', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'ILEANA', 'DI PIETRO', 'ileanadipietro@yahoo.it', '+393387074337', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'VERONICA', 'Iaquaniello', 'veronica.iaquaniello@gmail.com', '+393394957605', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Simona', 'Fedele', NULL, '+393804108994', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Giordano', 'Cimini', NULL, '+393459870227', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Eleonora', 'Roccasecca', 'eleonora.roccasecca@gmail.com', '+393456693173', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Alex', 'Sandro', NULL, '+393495142463', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Giacomo', 'Lupi', NULL, '+393456265866', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Luigi', 'Riva', NULL, '+393920829672', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Lamberto', 'Novara', NULL, '+393493272917', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Marco', 'Milletti', NULL, '+393421865986', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Elisabetta', 'Toselli', NULL, '+393287638736', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Azzurra', 'Evangelista', 'evangelistazzurra@gmail.com', '+393890903831', 'Donna', '2002-12-11', NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Jonathan', 'Paciotti', NULL, '+393479774289', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Matteo', 'Ciuffetta', 'ciuffettamatteo@gmail.com', '443473847342', 'Uomo', '2000-06-04', NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Marco', 'Montanari', 'mmontanarim3f74@gmail.com', '+393402386046', 'Uomo', '1974-02-03', NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Mariangela', NULL, NULL, '+393294239891', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Yasmine', NULL, NULL, '+393271194426', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Valentina', 'Facchin', NULL, '+393470024966', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Gianluca', 'Gasperoni', 'jallo@hotmail.it', '+393461335444', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Alessio', 'Massa', NULL, '+393450243092', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Mario', 'Crifo', NULL, NULL, NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Lorella', 'Varesi', NULL, '+393441389624', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Cristian', 'Ricco', NULL, '+393398914937', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Bea', 'Trix', 'beatrixxx94@gmail.com', '+393467369207', 'Uomo', '06-19', NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Jlenya', 'Cosmatsrl', 'cosmat.jlenya@gmail.com', '+393913991315', 'Donna', '1980-02-02', NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Erika', 'Palmieri', NULL, '+393391484675', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Valeria', 'Palladino', 'palladinovaleria@gmail.com', '+393208475965', NULL, '1985-06-04', NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Fabiana', 'Santoni', NULL, '+393336699014', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Fabio', 'Virgili', NULL, '+393475392292', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Ludovica', 'Bragaglia', NULL, '+393932603277', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Lesina', 'Maria', NULL, '+393475202281', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Maria', 'Segoloni', NULL, NULL, NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Erika', 'Giuliani', NULL, '+393936947775', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Ali', 'Abdallah', NULL, '+393497856191', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Gianluca', 'Bragaglia', NULL, '+393923888933', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Ludovica', 'Lupo', NULL, '+393885612551', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Simone', 'De Falco', NULL, '+393339552663', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Maria Jlenya', 'Colizzi', 'jlenya.colizzi@libero.it', '+393913991315', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Simona', 'Eleutueri', NULL, '+393491401462', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Andrea', 'Linari', NULL, '+393773278407', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Francesco', 'Linari', NULL, '+393499776394', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Tommaso', 'Favoriti', NULL, '+393890467721', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Lorenzo', 'Favoriti', NULL, '+393425586227', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Enrico', 'Nardi', NULL, '+393381870248', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Daniela', 'Tuzzolo', NULL, '+393485455132', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Salem', 'Abdall', NULL, '+393481268568', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Elena', 'Magni', NULL, '+393384977226', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Nikolas', 'Nanni', NULL, '+393500447386', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Martina', 'Santoni', NULL, '+393314704820', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Stefania', 'De Angelis', 'stefaniadeangelis23@gmail.com', '+393483632454', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Mirko', 'Bartelli', 'mirko.bartelli01@gmail.com', '+393276132109', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Ylenia', 'Rita', 'ritaylenia@gmail.com', '+393498479153', 'Donna', '07-17', NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Denise', 'Iozzi', NULL, '+393498935842', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Matteo', 'Ciuffetta', 'ciuffo0406@gmail.com', '+393473847342', 'Uomo', '2002-06-04', NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Leonardo', 'Del Proposto', NULL, '+393770888936', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Melissa', 'Trombetta', 'melissatrombetta53@hotmail.com', '+393807444861', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Maria', 'Gianeliu', NULL, '+393497381584', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Alida', 'Gozzi', NULL, '+393494149034', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Ylenia', 'Rita', 'yleniarita94@gmail.com', '+393498479153', 'Donna', '1994-07-17', NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Cinzia', 'Noviglio', NULL, '+393473929609', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Gabriele', 'Orlacchio', 'www.gabrieleorlacchio@gmail.com', '+393802165649', 'Uomo', '1999-12-27', NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Nicla', 'Lupo', 'ludovicalupo666@gmail.com', '+393285590765', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Azzurra', 'Evangelista', 'azzurrabirillo@gmail.com', '+393890903831', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Raffaele', 'Infiorata', NULL, '+393393101786', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Antonio', 'Palomba', NULL, '+393476229449', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Stefano', 'Perciballi', NULL, '+393473495511', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Marika', 'Di meo', NULL, '+393271766480', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Franco', 'Rossini', NULL, '+393485427028', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Giancarlo', 'Medoro', NULL, '+393292942012', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Matteo', 'Arbotto', NULL, '+393465397865', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Claudio', 'De Carolis', NULL, '+393403747865', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Giovanna', 'Locchi', NULL, '+393473922575', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Maria Chiara', 'Gavini', NULL, '+393453126767', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Mattia', 'Bernardi', NULL, '+393475035654', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Aleardo', 'Semprucci', NULL, '+393358135498', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Elisa', 'Locchi', NULL, '+393427033318', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Carmela', 'Rizzi', NULL, '+393407333973', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Daniele', 'Bartolocci', 'danielebartolocci@gmail.com', '+393296868699', 'Uomo', '1975-06-27', NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Domenico', 'Stamato', NULL, '+393804341999', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Claudia', 'Giovannetti', NULL, '+393474420991', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Cesare', 'Fini', NULL, '+393482566210', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Franca', 'Frezza', NULL, NULL, NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Andrea', 'Magnanimi', NULL, '+393805075411', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Antonietta', 'Marinelli', NULL, '+393474037117', NULL, NULL, '9.0 a 20 volumi it s color');
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Gianna', 'Pesciarelli', NULL, '+393664024337', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Alessio', 'De Palo', NULL, '+393663467872', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Rita', 'Bianchi', NULL, '+393476247241', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Tiziano', 'Trombetta', 'tiziano2000.tt@gmail.com', '+393452272043', 'Uomo', '1999-12-04', NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Andrea', 'Speranza', NULL, '+393920312719', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Pierpaolo', 'De santis', NULL, '+393331787293', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Maristella', 'Castri', NULL, '+393491550371', NULL, NULL, '80g di 6.0 + 40 gb7.0  20 volumi k-line');
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Debora', 'Pomponi', NULL, '+393479044484', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Giulia', 'Imbastari', NULL, '+393332874108', 'Donna', NULL, '9.00 Ox 20 volumi');
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Davide', 'Favale', '20davimiki11@gmail.com', '+393341198451', 'Uomo', '1992-02-21', NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Cristian', 'Ceschini', NULL, '+393475183624', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Filomena', 'Roccasecca', 'filomenaroccasecca1964@gmail.com', '+393487627374', NULL, NULL, 'BASE:80g di 5+15g di 6.1
LUNGHEZZE: 45g di 8.00+45g di 6.77 Ox 6vol');
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Tiziano', 'Pontieri', NULL, '+393284135386', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Manuel', 'Amici', NULL, '+393456034933', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Patrizia', 'Giovannetti', NULL, '+393493703990', NULL, NULL, '30 gr 8.00 + 30 gr 9.0 + 10 gr 10.1 a 20 volumi');
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Lucilla', 'Elle', 'lucillapace4@gmail.com', '+393493130297', 'Donna', '1969-05-21', 'BASE:10g di 7.40+10 g di 7.4+30 g di 6.34+30g di 8.34 Ox.20 volumi (ossigeno senza ammoniaca, colore One60nine)
LUNGHEZZA:50g di 8.34 Ox.10 volumi');
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Marco', 'Colazza', 'maguez94@live.it', '+393467114671', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Daniele', 'Di Tomassi', 'ditomassi88@gmail.com', '+393335440077', 'Uomo', '1988-05-23', NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'barbaradomeniconii@gmail.com', 'Domeniconi', 'barbaradomeniconii@gmail.com', '+393398682281', NULL, NULL, 'Artego its color
30 gr 8.0 + 30 gr 9.0 +10 gr 9S (linea one sixty nine) a 20 volumi');
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Giuseppe', 'Cattani', NULL, '+393314281973', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Daniele', 'Neri', 'danieleneri1997@gmail.com', '+393202883287', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Lorenzo', 'Remiddi', 'lollorem200@hotmail.com', '+393202457649', 'Uomo', '2001-04-21', NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Federico', 'Lommi', 'corey95@hotmail.it', '+393476245300', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Karen', 'Gramiccioli', NULL, '+393926708402', NULL, NULL, 'BASE 60g di 5.0+30 g di 5.1 a20 volumi
LUNGHEZZE 70g di 5.1 a 10 volumi');
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Marco', 'Orlacchio', 'marco.orlacchio@outlook.it', '+393884795302', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Monica', 'Sarais', '8marzotto@gmail.com', '+393395695664', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Francesco', 'De Falco', NULL, '+393770212687', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Riccardo', 'Del Proposto', NULL, '+393495131030', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Paola', 'Rotunno', NULL, NULL, NULL, NULL, '40g di 7 +30g di8.34+10g di 7.3 tutto senza ammoniaca ossigeno 80g a 30vol');
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Omar', 'Mohamed', 'mhmmro88@gmail.com', '+393396762993', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Riccardo', 'Beatrice', 'riccardo.bea94@gmail.com', '+393467369207', 'Uomo', '1994-06-19', NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Nicla', 'Lupo', 'niclaluposss@gmail.com', '+393285590765', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Lorenzo', 'Marinelli', 'famiglia.marinelli2021@outlook.it', '+393456024643', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Maria', 'Formiconi', 'formiconimaria@gmail.com', '+393284433856', NULL, NULL, '9.0 One60nine+ 15g di 9.1 One60nine');
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Gianluca', 'Peroni', 'g.peroni.1993@gmail.com', '+393400515605', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Jacopo', 'Cofini', 'jkap@hotmail.it', '+393281529542', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Andrea', 'Cignarella', 'acigna8@gmail.com', '+393485610015', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Lorenzo', 'Remiddi', 'loryumejo@hotmail.it', '+393202457649', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Elisa', 'Di meo', NULL, '+393804332978', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Marco', 'Fini', NULL, '+393406646945', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'sara', 'fagiolo', 'fagiolosara@gmail.com', '+393891756289', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Loredana', 'Fini', NULL, '+393883083733', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Anna', 'Cecconi', NULL, '+393477387880', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Rita', 'Frezza', 'frezzarita2@gmail.con', '+393351280766', NULL, NULL, '2 parti di n.6 + 1 parte di n.7 + 5g di 8.1 One60nine');
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Luciano', 'Pontieri', NULL, '+393351268669', NULL, NULL, NULL);
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Melissa', 'Trombetta', 'melissatrombetta53@gmail.com', '+393807444861', 'Donna', '1982-03-09', '50 g di 6+ 15g di 6.7+15g di 6.77 Ox 20 volumi');
INSERT INTO clients (business_id, user_id, first_name, last_name, email, phone, gender, birth_date, notes) VALUES (1, NULL, 'Angela', 'Baiocco', NULL, '+393487661413', NULL, NULL, '9.0+15g di n.9.1 One60nine');

-- Totale: 216 clienti importati
