analyzer:
  errors:
    deprecated_member_use: ignore
    library_private_types_in_public_api: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - avoid_print
    - prefer_single_quotes
